#!/bin/sh /etc/rc.common
#/etc/init.d/dail_zw
START=97
         
start() {           
       dail_3630  >> /etc/me3630/dail_init.log 2>&1
}      
stop(){                     
        killall dail_3630 >> /etc/me3630/dail_init.log 2>&1
}
